version: '3'

services:
  app:
    image: node:16-alpine
    volumes:
      - .:/app
    working_dir: /app
    env_file: ./.env
    depends_on:
      - database
      - cache
    command:
      - sh
      - -c
      - |
        npm i
        npm run dev

  database:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/database
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  cache:
    image: redis:6-alpine
    ports:
      - '6379:6379'

volumes:
  db-data:
